### ISSUE TITLE
Monitor websocket

### ISSUE THREAD

**Issue by D4nte** [status-im/infra-nim-waku#25]
We noticed issues with websockify that we were not able to resolve at this time.
Because websockify can have issues accepting secure websocket connections, it means that the TCP monitoring is not sufficient.

Ultimately, `websockify` should be sunset in favor of native websocket support in `wakunode2`, tracked with https://github.com/status-im/nim-waku/issues/434.

It is possible to use `curl` to test a secure websocket connection. However, the result is not _great_ for programmatic parsing:

```sh
▶ curl \
    --include \
    --no-buffer \
    --http1.1 \
    --header "Connection: Upgrade" \
    --header "Upgrade: websocket" \
    --header "Host: https://node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net:443" \
    --header "Origin: https://node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net:443" \
    --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
    --header "Sec-WebSocket-Version: 13" \
    https://node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net:443/
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=

�/multistream/1.0.0
^C
```

- SIGINT needs to be sent to stop the curl command
- if `multistream` is present in the output then it means that the websocket connection was successful (libp2p protocol negotiation started).

If this is not suitable, utility such as [websocat](https://github.com/vi/websocat) could be used instead.

**Comment by jakubgs** [comment]
Thanks for the example. Yeah, having to send `SIGINT` is quite bad, so I think I'd rather just use `websocat`.

**Comment by jakubgs** [comment]
Looks like `websocat` also needs a signal to stop communicating with the websocket:
```
admin@node-01.do-ams3.wakuv2.test:~ % websocat --no-async-stdio ws://localhost:443/    
/multistream/1.0.0
^C
```
Maybe one of the flags allows it to exit right away.

**Comment by jakubgs** [comment]
Okay, it's possible using combination of two flags:
```
admin@node-01.do-ams3.wakuv2.test:~ % websocat -1E ws://localhost:443/ 
/multistream/1.0.0
```
```
    -E, --exit-on-eof            Close a data transfer direction if the other one reached EOF
    -1, --one-message            Send and/or receive only one message. Use with --no-close and/or -u/-U.
```

**Comment by jakubgs** [comment]
For some reason I don't see the `/multistream/1.0.0` line when i run this via consul:
```json
        {
          "name": "nim-waku-v2-websocket Script check",
          "args": ["websocat", "-vt1E", "ws://localhost:443"],
          "interval": "30s",
          "timeout": "2s",
          "id": "nim-waku-v2-websocket"
        }
```
![image](https://user-images.githubusercontent.com/2212681/131477027-bf979c58-f586-4b14-9468-699f83296de5.png)

**Comment by jakubgs** [comment]
This makes no sense, when I run the same command in the shell I get it:
```
admin@node-01.do-ams3.wakuv2.test:~ % websocat -vk1E wss://node-01.do-ams3.wakuv2.test.statusim.net:443
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
/multistream/1.0.0
[INFO  websocat::sessionserve] Reverse finished
[INFO  websocat::sessionserve] One of directions finished
```

**Comment by jakubgs** [comment]
Fuck it, it's not like it's essential. We have the `-v` flag so we see it works from the `INFO` messages: https://github.com/status-im/infra-nim-waku/commit/87b340c2

Also updated metrics healthcheck to use the new `/health` endpoint: https://github.com/status-im/infra-nim-waku/commit/449d76b0
