### ISSUE TITLE
Deploy Waku v2 `prod` nodes list to DNS provider

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-nim-waku#29]
UPDATE (original description follows below, but is outdated):

After [Release v0.7](https://github.com/status-im/nim-waku/releases/tag/v0.7) the `nim-waku` prod list to be deployed to a DNS provider, in zone file format:
```
; name                        ttl     class type  content
@                             60      IN    TXT   enrtree-root:v1 e=2FPT7YBR4ZHGPTSEDRD5D6N7MU l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=6fuJ5SvsUX_9se681PVe2ZToyTfkm6WHTD9hoy3RhFtDMTD2ZvxgJ3V1283aFhBsftch0T3UvKohWM404A7eIgE
FDXN3SN67NA5DKA4J2GOK7BVQI    86900   IN    TXT   enrtree-branch:
2FPT7YBR4ZHGPTSEDRD5D6N7MU    86900   IN    TXT   enrtree-branch:MFAJGGC6CLWF6CXCR2V6CNED7Q,QHKIV5TAXBC6N24HILY7ASGSFU,WTAZHIHIXAEAFB4KVC7SNBIFLU
MFAJGGC6CLWF6CXCR2V6CNED7Q    86900   IN    TXT   enr:-Iu4QJUcYA1ULMF9UfwOZBLNPT0dSxrVtGRws6KhE9b3WH9IS-1gAfTSzJjm30gp3Wz46upPJbdarGOIZTNlG3k_n0YBgmlkgnY0gmlwhAjS3ueJc2VjcDI1NmsxoQKNAvlb34B4l68WYt7pg4qKFzBmPRb2I-f3dUOBHku3soN0Y3CCdl-Fd2FrdTIP
QHKIV5TAXBC6N24HILY7ASGSFU    86900   IN    TXT   enr:-Iu4QALmEco5FZq1DDf3egW27AJ6YSg4Rpdp3RJxQlLQbdrNDxsYJXIVH8ZUh346EVOldWhxr8zoiyfBwJPDgPoNoOsBgmlkgnY0gmlwhLymh5GJc2VjcDI1NmsxoQNuXVf_MkjDcQAka2YcxWfhnbGGlKhRo_kSWwcoK_uGVYN0Y3CCdl-Fd2FrdTIP
WTAZHIHIXAEAFB4KVC7SNBIFLU    86900   IN    TXT   enr:-Iu4QE2RvpRiwWwoCf-EkwCx25_ftH5VOiv67bp2gO1qzi6yKzYMV3ZrG4JDEOyJuZs5miH-nRtM3r48ksb6QL2gvWYBgmlkgnY0gmlwhCJ5ZGyJc2VjcDI1NmsxoQP99JB4EKn12UYqGuCf7uWrIF0yeYsP_MN5RCAh-Exbv4N0Y3CCdl-Fd2FrdTIP
```

This must be deployed to:
`prod.waku.nodes.status.im`

The public key used to sign this list is:
`ANTL4SLG2COUILKAPE7EF2BYNL2SHSHVCHLRD5J7ZJLN5R3PRJD2Y`

The list can then be accessed, verified and linked to other trees using the URL:
`enrtree://ANTL4SLG2COUILKAPE7EF2BYNL2SHSHVCHLRD5J7ZJLN5R3PRJD2Y@prod.waku.nodes.status.im`

cc @richard-ramos @D4nte 

-----------
> **_NB:_** everything below serves only as background. The list to be deployed and DNS domain is set out in the updated section above.

### Background

[Release v0.6](https://github.com/status-im/nim-waku/releases/tag/v0.6) of `nim-waku` includes node discovery via DNS. This allows new nodes to discover a bootstrap list of Waku v2 peers to connect to using DNS queries. The list is encoded as a Merkle tree and deployed in TXT records to a DNS provider according to [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459).

We have [previously deployed](https://github.com/status-im/infra-nim-waku/issues/23) such a list for the `test` fleet. Since the release, this is now available for the `prod` fleet as well.

### List to deploy to DNS provider

In zone file format:
```
; name                        ttl     class type  content
@                             60      IN    TXT   enrtree-root:v1 e=CYNE2WDADG4RP2UTJGMHMQZK6I l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=DRT5-3_lQdnSiD3Uw_kapkqyq6W4aimj8nu_4IDSYix8DA4-h318AUDcx2_2aZ0PTT85n75-6LVUkF4rig3fLwA
FDXN3SN67NA5DKA4J2GOK7BVQI    86900   IN    TXT   enrtree-branch:
CYNE2WDADG4RP2UTJGMHMQZK6I    86900   IN    TXT   enrtree-branch:M5XMY2Q5CSBCKPPR6IUAXNDMBE,IJ27VGBIE5LC42G4HNWQW6UR7A,4GZP2NQGNRHCKQ22ZCUFSPJZW4
IJ27VGBIE5LC42G4HNWQW6UR7A    86900   IN    TXT   enr:-IS4QLi9BXG9ysPjAC1ZJfgCW_RuGZXX6oOSG7S93P7ioSDRbzFeZhW0SxmjpTMBRCUFuBDUM88Q9jc1XZi3Qfo4XdEBgmlkgnY0gmlwhLymh5GJc2VjcDI1NmsxoQNuXVf_MkjDcQAka2YcxWfhnbGGlKhRo_kSWwcoK_uGVYN0Y3CCdl8
M5XMY2Q5CSBCKPPR6IUAXNDMBE    86900   IN    TXT   enr:-IS4QD61QfYLaKgo3wwAeNOk23yCGV8ujcix0iYdgJUNj32eWJymXSTTXyL_sIrDpcIImovpVX5dby1Tf71FL12ZyvoBgmlkgnY0gmlwhAjS3ueJc2VjcDI1NmsxoQKNAvlb34B4l68WYt7pg4qKFzBmPRb2I-f3dUOBHku3soN0Y3CCdl8
4GZP2NQGNRHCKQ22ZCUFSPJZW4    86900   IN    TXT   enr:-IS4QECyE7awbeqDqZurmKfl1qHnlkWcCIebx8JcLPiE3cnmKB_sP8n_7QDaNWHNc1inPRk-Zk6H5jVOsBmDPdk0MRsBgmlkgnY0gmlwhCJ5ZGyJc2VjcDI1NmsxoQP99JB4EKn12UYqGuCf7uWrIF0yeYsP_MN5RCAh-Exbv4N0Y3CCdl8
```

### Where to deploy

The list above should be deployed against four different domain names. This is because of [a Desktop requirement](https://forum.vac.dev/t/desktop-requirements-for-wakuv2/105/10) to distinguish between nodes for each of Waku's four main protocols. Although we currently have the same three `prod` nodes for all 4 main Waku protocols, it's reasonable to expect these lists to diverge once user-run nodes are added for some protocols.

The chosen (sub)domain names should:
1) not be associated with `vac` as a team, but rather indicate `waku`
2) differentiate lists for our main protocols: `relay`, `store`, `filter`, `lightpush`.

My suggestion is therefore to deploy the list at:
- `relay.waku.nodes.status.im`
- `store.waku.nodes.status.im`
- `filter.waku.nodes.status.im`
- `lightpush.waku.nodes.status.im`

I'd like to get @richard-ramos and @oskarth comments here as well about choice of domain.

### The future of key management for DNS discovery

Currently this list is signed by a password-protected key on my local system, which is far from ideal, especially if we want to update these lists. We need to deploy [the tree creator utility](https://github.com/status-im/nim-dnsdisc/blob/main/docs/tutorial.md) somewhere where it can be initialised with a Status-managed key. This requires some modifications to the existing utility. Tracking issue [here](https://github.com/status-im/nim-dnsdisc/issues/10).

**Comment by oskarth** [comment]
Seems OK, but some reservations.

One concern here is in terms of solidifying Status nodes as special and being too strict with stuff like subdomains per protocol. Another is to make it seem normal to have DNS Discovery entries for a lot of nodes, as opposed to primarily function as bootstrap nodes. Of course, there'll likely be a in-between stage where these are the same thing. If we pair it with a crawling mechanism it might be OK to not just have bootstrap nodes here.

> once user-run nodes are added for some protocols.

How do we see this growing organically? If a community, say, starts to add nodes will there be some process for adding their nodes to each of these 4 subdomains?

One user story that would be good to support is: Community runs a bunch of nodes and exposes them as a subtree. They can be added to desktop through two ways:

1) User enters a new / additional DNS root to circumvent Status cluster as source of truth
2) Community goes to Status dev multisig / community governance and gets it added as subtree there for automatic discovery of desktop users

In both cases, do we expect the community nodes to follow a strict schema of `{lightpush,relay,...}.FooCommunity.eth.link`? If they don't, shouldn't the client be able to connect to all (bootstrap) nodes, see what protocols they support and then sort them into buckets locally based on this?

How do other projects, like Ethereum, use DNS discovery in practice? Looking briefly I see https://github.com/ethereum/discv4-dns-lists/blob/master/all.goerli.ethdisco.net/nodes.json where they have `all` and `les` lists per network, then they crawl to auto update with community nodes. That might be a reasonable approach.

Given above, what would the downside be of keeping it as simple as possible? A client then connects to all nodes and sorts into buckets depending on protocol support response. Then it can cache across restarts etc.

cc @jakubgs @iurimatias

**Comment by jm-clius** [comment]
Right. These are good points. We don't want to add an innovation that ends up making it more difficult to use/add to the lists because it's inflexible.

In my mind it's not clear how likely it is that highly-available user-run nodes (i.e. suitable for bootstrapping) will want to make themselves discoverable via DNS. If they do make themselves available in large numbers, the concern would be that they skew heavily towards `relay` (or even `filter` and `lightpush`), but not `store` because of its resource intensity. The per-protocol domains above are meant to avoid a situation where a new node would have to cycle through a long list of bootstrap nodes before finding a suitable `store`. Of course, once this happens we'd hopefully have other capability discovery mechanisms  available to solve the issue (such as publishing `store` nodes to a separate topic).

> How do we see this growing organically? If a community, say, starts to add nodes will there be some process for adding their nodes to each of these 4 subdomains?

Yes, rough idea is that through some TBD community consensus mechanism, new and trusted nodes can be added individually or as subtrees to the existing lists. It's also possible to add links to other trees in different domains to the existing domain lists.

> One user story that would be good to support
> 1. User enters a new / additional DNS root
> 2. Community goes to Status dev multisig / community governance and gets it added as subtree

I agree. (1) we already support on the Waku layer and (2) is more or less how I see community-run nodes being added to the lists (with the added possibility to just add link to other trees at other domains in our list.

> then they crawl to auto update with community nodes

Could work! Though such lists will (likely) skew heavily towards `relay` which highlights again the importance of a parallel capability discovery mechanism for bootstrapping.

> Given above, what would the downside be of keeping it as simple as possible?

My own conclusion: not much. My concerns above are to address a problem, which:
a) we do not yet have
b) we should address with capability discovery in any case

The only remaining question is if it makes sense from Desktop's perspective to run `identify` after discovery to sort the nodes into protocol buckets. @richard-ramos

**Comment by richard-ramos** [comment]
I don't see many issues with changing the code so status-go runs identify protocol against all the nodes returned in DNS discovery. What I'm not sure of is if there's a noticeable impact in time before status-go is able to send/receive messages since we need to wait for identify protocol to finish before knowing what nodes are available for relay/store/filter/lightpush.

**Comment by jm-clius** [comment]
> if there's a noticeable impact in time before status-go is able to send/receive messages since we need to wait for identify protocol to finish before knowing what nodes are available for relay/store/filter/lightpush

@richard-ramos, any closer to an answer given the recent dogfooding off `test`? Not sure how feasible this is in `status-go`, but does this "bootstrap nodes state" persist across restarts?

**Comment by D4nte** [comment]
> If a community, say, starts to add nodes will there be some process for adding their nodes to each of these 4 subdomains?

I agree with this question. If we have a dApp dev that uses Waku and decides to support the network by running nodes. We want to make it as easy as possible to add this nodes to the status domain so other can bootstrap to them.
This should be done by them referencing their node in their own domain and linking their domain to the status/vac one.

They can then update their domain if they change their nodes (or their community run more node).

As we haven't yet tested this strategy, I am worried about adding a layer of complexity that could be solved by using the identify protocol.

I think it'd be easier to have one domain name for now and review if and when we actually hit some issues around not discovering a store node, etc.

**Comment by jm-clius** [comment]
Currently awaiting next release: https://github.com/status-im/nim-waku/issues/808 before deploying

**Comment by jm-clius** [comment]
@jakubgs, now that the release has been deployed to `prod`, we can go ahead and deploy the `prod` nodes list to a DNS provider. Details below. I've also updated the issue description, since the previous discussion is now outdated.

In zone file format:
```
; name                        ttl     class type  content
@                             60      IN    TXT   enrtree-root:v1 e=2FPT7YBR4ZHGPTSEDRD5D6N7MU l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=6fuJ5SvsUX_9se681PVe2ZToyTfkm6WHTD9hoy3RhFtDMTD2ZvxgJ3V1283aFhBsftch0T3UvKohWM404A7eIgE
FDXN3SN67NA5DKA4J2GOK7BVQI    86900   IN    TXT   enrtree-branch:
2FPT7YBR4ZHGPTSEDRD5D6N7MU    86900   IN    TXT   enrtree-branch:MFAJGGC6CLWF6CXCR2V6CNED7Q,QHKIV5TAXBC6N24HILY7ASGSFU,WTAZHIHIXAEAFB4KVC7SNBIFLU
MFAJGGC6CLWF6CXCR2V6CNED7Q    86900   IN    TXT   enr:-Iu4QJUcYA1ULMF9UfwOZBLNPT0dSxrVtGRws6KhE9b3WH9IS-1gAfTSzJjm30gp3Wz46upPJbdarGOIZTNlG3k_n0YBgmlkgnY0gmlwhAjS3ueJc2VjcDI1NmsxoQKNAvlb34B4l68WYt7pg4qKFzBmPRb2I-f3dUOBHku3soN0Y3CCdl-Fd2FrdTIP
QHKIV5TAXBC6N24HILY7ASGSFU    86900   IN    TXT   enr:-Iu4QALmEco5FZq1DDf3egW27AJ6YSg4Rpdp3RJxQlLQbdrNDxsYJXIVH8ZUh346EVOldWhxr8zoiyfBwJPDgPoNoOsBgmlkgnY0gmlwhLymh5GJc2VjcDI1NmsxoQNuXVf_MkjDcQAka2YcxWfhnbGGlKhRo_kSWwcoK_uGVYN0Y3CCdl-Fd2FrdTIP
WTAZHIHIXAEAFB4KVC7SNBIFLU    86900   IN    TXT   enr:-Iu4QE2RvpRiwWwoCf-EkwCx25_ftH5VOiv67bp2gO1qzi6yKzYMV3ZrG4JDEOyJuZs5miH-nRtM3r48ksb6QL2gvWYBgmlkgnY0gmlwhCJ5ZGyJc2VjcDI1NmsxoQP99JB4EKn12UYqGuCf7uWrIF0yeYsP_MN5RCAh-Exbv4N0Y3CCdl-Fd2FrdTIP
```

This must be deployed to:
`prod.waku.nodes.status.im`

This list can then be accessed, verified and linked to other trees using the URL:
`enrtree://ANTL4SLG2COUILKAPE7EF2BYNL2SHSHVCHLRD5J7ZJLN5R3PRJD2Y@prod.waku.nodes.status.im`

**Comment by jakubgs** [comment]
Done: https://github.com/status-im/infra-nim-waku/commit/f4ed8b12
```
 > dig +short TXT prod.waku.nodes.status.im 
"enrtree-root:v1 e=2FPT7YBR4ZHGPTSEDRD5D6N7MU l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=6fuJ5SvsUX_9se681PVe2ZToyTfkm6WHTD9hoy3RhFtDMTD2ZvxgJ3V1283aFhBsftch0T3UvKohWM404A7eIgE"
```

**Comment by jm-clius** [comment]
Thanks, Jakub!
