### ISSUE TITLE
Deploy updated Waku v2 `test` nodes list to DNS provider

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-nim-waku#34]
## Background

This issue relates to #29.
We previously deployed a discoverable list for the `wakuv2.test` fleet to a DNS provider, following [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459). Since then:
1. the format of the deployed ENRs have evolved to include more information, including `wss` addresses. This follows [RFC 31](https://rfc.vac.dev/spec/31/).
2. we have decided to move away from a Vac-specific domain (`test.nodes.vac.dev`) to `test.waku.nodes.status.im`

This necessitates deploying an updated list for the `test` fleet to the new domain. Once the latest release has been installed on `prod`, a list will be deployed for that too (tracked in #29, blocked by https://github.com/status-im/nim-waku/issues/808).

## List to deploy to DNS provider

In zone file format:
```
; name                        ttl     class type  content
@                             60      IN    TXT   enrtree-root:v1 e=SLJBDRNPBTM7X5RSO4WH25IDJY l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=zQ0_i4YO91B6wJ9doGoOLKb-V-stM8RdZAmnqSFtwKA8NAx6IbK-k-rRR3vrC5xzDDEFDUYCpC5--OvhKHgr8gA
FDXN3SN67NA5DKA4J2GOK7BVQI    86900   IN    TXT   enrtree-branch:
SLJBDRNPBTM7X5RSO4WH25IDJY    86900   IN    TXT   enrtree-branch:3JSK24BF37BTAFHD4PAHCWBDOY,LECZMNF5HMUHARM32YUF7RH3OE,26XUO2RSK7DWIGSTCBP4DQAH5Y
3JSK24BF37BTAFHD4PAHCWBDOY    86900   IN    TXT   enr:-KO4QBlzNVtUWMCNvsMkslFNSpa67cDaLXrXkMdGRddToD3jcRfEEi345NV6h56-rXO3C8oMxZ44UaZfJL10Tm7U8vMBgmlkgnY0gmlwhIbRi9KKbXVsdGlhZGRyc4wACgSG0YvSBh9A3gOJc2VjcDI1NmsxoQOevTdO6jvv3fRruxguKR-3Ge4bcFsLeAIWEDjrfaigNoN0Y3CCdl-Fd2FrdTIP
LECZMNF5HMUHARM32YUF7RH3OE    86900   IN    TXT   enr:-KO4QBzUhElxiM-NSjSA1B4iEkFw3_SZj-Q18jPfvruKTLy9Na3VgbUwVMFOXcvMylAB_2C6uesZJSHm99FbFqir6-0BgmlkgnY0gmlwhGia74CKbXVsdGlhZGRyc4wACgRomu-ABh9A3gOJc2VjcDI1NmsxoQNYImLJllfa9siWWAIjBhyX4y5S3qgLkwKJFBjzf_6ZMYN0Y3CCdl-Fd2FrdTIP
26XUO2RSK7DWIGSTCBP4DQAH5Y    86900   IN    TXT   enr:-KO4QFi0j_vwI2p4j9lPn_mCEPCx3G32ZQt1uTd8aql6chBncFQqbu5m6sW18mwpidE_Fn1U_5RrtWmqwWpVRicH9TIBgmlkgnY0gmlwhC_y0kmKbXVsdGlhZGRyc4wACgQv8tJJBh9A3gOJc2VjcDI1NmsxoQIQJvj-KupljjSnBp2yz1PFl2SeELNwMSG68nL3Oz1SrIN0Y3CCdl-Fd2FrdTIP
```

## Where to deploy

`test.waku.nodes.status.im`, if possible

cc @D4nte @richard-ramos - the list contains the updated ENRs for the `test` fleet, including the `waku2` and `multiaddrs` fields. Note the proposed change in domain. The tree can still be accessed and verified using the previous public key, i.e. `AOFTICU2XWDULNLZGRMQS4RIZPAZEHYMV4FYHAPW563HNRAOERP7C@test.waku.nodes.status.im`

**Comment by jakubgs** [comment]
Change: https://github.com/status-im/infra-nim-waku/commit/f1b6b9e2
```
 > dig +short TXT test.waku.nodes.status.im 
"enrtree-root:v1 e=SLJBDRNPBTM7X5RSO4WH25IDJY l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=zQ0_i4YO91B6wJ9doGoOLKb-V-stM8RdZAmnqSFtwKA8NAx6IbK-k-rRR3vrC5xzDDEFDUYCpC5--OvhKHgr8gA"

 > dig +short TXT SLJBDRNPBTM7X5RSO4WH25IDJY.test.waku.nodes.status.im 
"enrtree-branch:3JSK24BF37BTAFHD4PAHCWBDOY,LECZMNF5HMUHARM32YUF7RH3OE,26XUO2RSK7DWIGSTCBP4DQAH5Y"

 > for ID in "3JSK24BF37BTAFHD4PAHCWBDOY" "LECZMNF5HMUHARM32YUF7RH3OE" "26XUO2RSK7DWIGSTCBP4DQAH5Y"; do
     dig +short TXT $ID.test.waku.nodes.status.im;
   done 
"enr:-KO4QBlzNVtUWMCNvsMkslFNSpa67cDaLXrXkMdGRddToD3jcRfEEi345NV6h56-rXO3C8oMxZ44UaZfJL10Tm7U8vMBgmlkgnY0gmlwhIbRi9KKbXVsdGlhZGRyc4wACgSG0YvSBh9A3gOJc2VjcDI1NmsxoQOevTdO6jvv3fRruxguKR-3Ge4bcFsLeAIWEDjrfaigNoN0Y3CCdl-Fd2FrdTIP"
"enr:-KO4QBzUhElxiM-NSjSA1B4iEkFw3_SZj-Q18jPfvruKTLy9Na3VgbUwVMFOXcvMylAB_2C6uesZJSHm99FbFqir6-0BgmlkgnY0gmlwhGia74CKbXVsdGlhZGRyc4wACgRomu-ABh9A3gOJc2VjcDI1NmsxoQNYImLJllfa9siWWAIjBhyX4y5S3qgLkwKJFBjzf_6ZMYN0Y3CCdl-Fd2FrdTIP"
"enr:-KO4QFi0j_vwI2p4j9lPn_mCEPCx3G32ZQt1uTd8aql6chBncFQqbu5m6sW18mwpidE_Fn1U_5RrtWmqwWpVRicH9TIBgmlkgnY0gmlwhC_y0kmKbXVsdGlhZGRyc4wACgQv8tJJBh9A3gOJc2VjcDI1NmsxoQIQJvj-KupljjSnBp2yz1PFl2SeELNwMSG68nL3Oz1SrIN0Y3CCdl-Fd2FrdTIP"
```
Tell me when I can remove the legacy entries.

**Comment by jm-clius** [comment]
Thanks, Jakub!

@richard-ramos @D4nte, the updated records for the `wakuv2.test` fleet is now available at `test.waku.nodes.status.im`. LMK if you're not using `test.nodes.vac.dev` anymore, so we can remove those entries.

**Comment by D4nte** [comment]
> Thanks, Jakub!
> 
> @richard-ramos @D4nte, the updated records for the `wakuv2.test` fleet is now available at `test.waku.nodes.status.im`. LMK if you're not using `test.nodes.vac.dev` anymore, so we can remove those entries.

The Vac entries can be removed from js-waku POV

**Comment by richard-ramos** [comment]
I created a couple of PRs for desktop that include this change. Once those are merged, we can remove the entries.
Thank you!

**Comment by jm-clius** [comment]
Seems like the required changes have been merged. @jakubgs, I think the next step is to remove the entries at `test.nodes.vac.dev` and then this issue can be closed. Thanks!

**Comment by jakubgs** [comment]
Done: https://github.com/status-im/infra-nim-waku/commit/f5d172c61
