### ISSUE TITLE
CPU and memory usage spikes on hosts

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nim-waku#36]
I've been seeing some big spikes in resource usage on some hosts that cause them to become inaccessible:

![image](https://user-images.githubusercontent.com/2212681/151209753-0cbdebad-81b5-4cc0-b937-cdf9beb7517d.png)

In this case it's `node-01.gc-us-central1-a.wakuv2.prod`, but I've seen it on other hosts.

**Comment by jakubgs** [comment]
There is not corresponding spike in traffic though:

![image](https://user-images.githubusercontent.com/2212681/151209906-e8f0971d-6a2f-4eb6-8e97-34fcd46a4507.png)

**Comment by jakubgs** [comment]
But definitely a big spike in disk utilization:

![image](https://user-images.githubusercontent.com/2212681/151209977-08b5c18d-d63d-4383-9f47-4b9e98dc63b5.png)

**Comment by jakubgs** [comment]
Growth in CPU time spent on `iowait` grows to match:

![image](https://user-images.githubusercontent.com/2212681/151210285-db63a6c5-415c-42f1-8938-cad387a84cc3.png)

**Comment by jm-clius** [comment]
Since it's mostly IO reads, I'm wondering if it's related to swapping due to the service running out of memory. I'll try to see what I can detect.

**Comment by jakubgs** [comment]
After multiple failed attempts:
```
 > ssh node-01.gc-us-central1-a.wakuv2.prod docker restart nim-waku-v2
Timeout, server node-01.gc-us-central1-a.wakuv2.prod not responding.
```
I've managed to restart the container and free up the resources.

**Comment by jakubgs** [comment]
It appears that before the full spike there was increase in waku messages:

![image](https://user-images.githubusercontent.com/2212681/151221361-d1328beb-a401-406a-9340-f0c20ebd5040.png)

We can see the increase started around 16:00 UTC, and that matches with the "Container Throttle IO" graph above.

**Comment by jakubgs** [comment]
Now the same thing happened to `node-01.ac-cn-hongkong-c.wakuv2.prod`:

![image](https://user-images.githubusercontent.com/2212681/151241651-96c1fe6f-8138-4772-96cd-d4e7fff6d3d2.png)

**Comment by jakubgs** [comment]
I'm tempted to disable alerts on `nim-waku` fleets, because this shit happens every few hours. It's really getting on my nerves:

![image](https://user-images.githubusercontent.com/2212681/151618314-08bff41c-92c9-4e06-a45a-d0ba050b0839.png)

**Comment by jakubgs** [comment]
I received 19 alerts from `wakuv2.prod` fleet last night, I'm done. I'm putting those servers in maintenance mode:

```
~/work/infra-nim-waku master*
 > a all -a 'consul maint -enable -reason="flaky as fuck"'  
node-01.do-ams3.wakuv2.prod | CHANGED | rc=0 >>
Node maintenance is now enabled
node-01.gc-us-central1-a.wakuv2.prod | CHANGED | rc=0 >>
Node maintenance is now enabled
node-01.ac-cn-hongkong-c.wakuv2.prod | CHANGED | rc=0 >>
Node maintenance is now enabled
```

**Comment by jakubgs** [comment]
The prod nodes have restarted due to this issue __21__ times in the last 7 days:

![image](https://user-images.githubusercontent.com/2212681/151767842-d8592b4b-c364-455f-ae6c-67ae2ab8f741.png)

This is getting silly.

**Comment by jakubgs** [comment]
We can see this started happening after 19th of January:
![image](https://user-images.githubusercontent.com/2212681/151780355-3bb6803f-a432-406e-89a8-79ac923394b1.png)

**Comment by jakubgs** [comment]
I see tree CI builds from 2022/01/19:

* https://ci.status.im/job/nim-waku/job/deploy-v2-prod/23/ - https://github.com/status-im/nim-waku/commit/81f89b5bc17fc1b81248a66d650ee4e6b588935b
* https://ci.status.im/job/nim-waku/job/deploy-v2-prod/24/ - https://github.com/status-im/nim-waku/commit/81f89b5bc17fc1b81248a66d650ee4e6b588935b
* https://ci.status.im/job/nim-waku/job/deploy-v2-prod/25/ - https://github.com/status-im/nim-waku/commit/81f89b5bc17fc1b81248a66d650ee4e6b588935b

All three deploy the same commit: `Release v0.7` (https://github.com/status-im/nim-waku/pull/818)

**Comment by jakubgs** [comment]
Here we can see how we are running out of memory and SWAP every ~30-40 hours:

![image](https://user-images.githubusercontent.com/2212681/151782759-0d02d280-b388-4547-9615-0bc9e3c7dc51.png)

**Comment by jakubgs** [comment]
If we compare that graph against 7 days of messages per minute it looks to me like a memory leak:

![image](https://user-images.githubusercontent.com/2212681/151783988-c7905b02-52a7-4e13-be5f-23d08c97c531.png)

**Comment by jakubgs** [comment]
lt's worth noting that the `wakuv2.test` fleet does not show this pattern of memory usage:

![image](https://user-images.githubusercontent.com/2212681/151784152-ff106d57-01d8-4b8d-881d-6049156f48e9.png)

But that's most probably due to absolutely tiny volume of messages:

![image](https://user-images.githubusercontent.com/2212681/151784288-d0e5fa69-ab43-45fc-b3e7-31f6289b1841.png)

**Comment by jakubgs** [comment]
@jm-clius will you open an issue for this in `nim-waku` for this memory leak, or should we transfer this issue to `nim-waku` repo?

**Comment by jm-clius** [comment]
Thanks, @jakubgs. Back tomorrow and will then create a linked issue in nim-waku.

**Comment by jakubgs** [comment]
I've bumped the DigitalOcean and Alibaba Cloud hosts to have 2 GB of ram: https://github.com/status-im/infra-nim-waku/commit/935b00d2
Also increased container limits to 70%: https://github.com/status-im/infra-nim-waku/commit/71982b78
And the reduction of store capacity to 10k from @jm-clius: https://github.com/status-im/infra-nim-waku/pull/37

**Comment by jm-clius** [comment]
Thanks, @jakubgs. This really seems to have worked.

**Comment by jakubgs** [comment]
It's too early to call it just yet, we'll see after the weekend, the pattern is still there, we just have more memory:

![image](https://user-images.githubusercontent.com/2212681/152511733-d076d520-8b4e-4e63-b787-1a9e780d19a6.png)

**Comment by jakubgs** [comment]
Nope, still happening, just less frequently:

![image](https://user-images.githubusercontent.com/2212681/152765749-784d817a-35b7-488a-9c8f-c39e733e56dc.png)

Also, looks like container metrics broke for some reason:

![image](https://user-images.githubusercontent.com/2212681/152765954-38d8d5b1-8c2a-4d18-acf7-a49efed66e55.png)

@jm-clius I don't think we're out of the woods yet. This needs a proper solution int he code.

**Comment by jakubgs** [comment]
I bumped SWAP file size to 2 GB to match RAM size: https://github.com/status-im/infra-nim-waku/commit/b82b6acb

**Comment by jm-clius** [comment]
> @jm-clius I don't think we're out of the woods yet. This needs a proper solution int he code.

Yeah, I was hoping it'd take a little bit longer to reach this point again, but you're right. It needs to be fixed in code.

Tracking here: https://github.com/status-im/nim-waku/issues/838

**Comment by jm-clius** [comment]
(Accidentally closed, while just trying to add a comment.)
