### ISSUE TITLE
enrtree's multiaddrs do not match SSL cert

### ISSUE THREAD

**Issue by D4nte** [status-im/infra-nim-waku#38]
Regarding the enr tree stored at `test.waku.nodes.status.im`.

The values stored in the `multiaddrs` field of the various ENR records are as follow:

- `/ip4/134.209.139.210/tcp/8000/wss`
- `/ip4/104.154.239.128/tcp/8000/wss`
- `/ip4/47.242.210.73/tcp/8000/wss`

However, the SSL certificates used are letsencrypt certificates

https://github.com/status-im/infra-nim-waku/blob/e6fad0fbdea1ed98f849cb94b0896d1eb7a137a9/ansible/group_vars/wakuv2-test.yml#L27

That have for `Subject Alt Names` the fqdn of the host:

`DNS Name: node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net`

Hence, the certificates are not valid for the given multiaddresses as the certificates do not certify the nodes' ip (contains in the multiaddr) are not.

## Proposed solution

Update the ENR tree to contains `dns4` multiaddresses in the `multiaddrs` field.

Note: Only js-waku should be using the websocket multiaddrs so the lack of `dns4` support of nim-waku should not block this issue (afaik).

Cc @jm-clius

**Comment by jm-clius** [comment]
Ah, right. Thanks for reporting. This should be fixed.

**Comment by jakubgs** [comment]
Is this still valid?

**Comment by D4nte** [comment]
It looks fixed
