### ISSUE TITLE
DNS4 domain name for `wakuv2.test` fleet

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-nim-waku#41]
### Background

We recently added the ability to configure a nim-waku node with an (ipv4) domain name.
This allows for the node's publically announced multiaddrs to use the `/dns4/` scheme. In addition, nodes with domain name and secure websocket configured, will generate a discoverable ENR containing the wss multiaddr with `/dns4/` domain name. This is necessary to verify domain certificates when connecting to this node over secure websocket and is a prerequisite for addressing https://github.com/status-im/infra-nim-waku/issues/38

### Required change

For the `wakuv2.test` fleet:
Add config option
`--dns4-domain-name=<node domain>`

e.g. the effective config option for the node on `node-01.do-ams3.wakuv2.test` should be:
`--dns4-domain-name=node-01.do-ams3.wakuv2.test.statusim.net`

This option is not yet available on the `prod` fleet, but will be after the release: https://github.com/status-im/nim-waku/issues/870. If we encounter no issues with this config on `wakuv2.test` we can apply the same to `wakuv2.prod` after the release.

More documentation at https://github.com/status-im/nim-waku/tree/master/waku/v2#configuring-a-domain-name

**Comment by jakubgs** [comment]
I see the change required is https://github.com/status-im/nim-waku/pull/852 and we're on https://github.com/status-im/nim-waku/commit/c27086e1 so test fleet is ready.

**Comment by jm-clius** [comment]
Correct. Thanks, Jakub. Test fleet has the config option available already. Aiming to get release done and deployed to `prod` by Wednesday.

**Comment by jakubgs** [comment]
Question: Does this flag affect only Websocket multiaddress or also Libp2p multiaddress?

**Comment by jakubgs** [comment]
Changes:

- https://github.com/status-im/infra-role-nim-waku/commit/0229249c - add support for --dns4-domain-name flag
- https://github.com/status-im/infra-nim-waku/commit/91519c24 - configure --dns4-domain-name flag

Done:
```
 > a all -a 'grep dns4 /docker/nim-waku-v2/docker-compose.yml' 
node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
      --dns4-domain-name=node-01.do-ams3.wakuv2.test.statusim.net
node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
      --dns4-domain-name=node-01.gc-us-central1-a.wakuv2.test.statusim.net
node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
      --dns4-domain-name=node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net
```
