### ISSUE TITLE
DNS4 domain names for `wakuv2.prod` fleet

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-nim-waku#45]
### Background

We added `dns4` domain name config for the `wakuv2.test` fleet in https://github.com/status-im/infra-nim-waku/issues/41. This option is now available for the `wakuv2.prod` fleet as well and must be added to the configuration.
This allows for the node's publically announced multiaddrs to use the `/dns4/` scheme.

### Required change

For the `wakuv2.prod` fleet:
Add config option
`--dns4-domain-name=<node domain>`

e.g. the effective config option for the node on `node-01.ac-cn-hongkong-c.wakuv2.prod` should be:
`--dns4-domain-name=node-01.ac-cn-hongkong-c.wakuv2.prod.statusim.net`

More documentation at https://github.com/status-im/nim-waku/tree/master/waku/v2#configuring-a-domain-name

**Comment by jakubgs** [comment]
Done: https://github.com/status-im/infra-nim-waku/commit/a0796fc4
```
 > a all -a 'grep dns4-domain /docker/nim-waku-v2/docker-compose.yml'
node-01.do-ams3.wakuv2.prod | CHANGED | rc=0 >>
      --dns4-domain-name=node-01.do-ams3.wakuv2.prod.statusim.net
node-01.gc-us-central1-a.wakuv2.prod | CHANGED | rc=0 >>
      --dns4-domain-name=node-01.gc-us-central1-a.wakuv2.prod.statusim.net
node-01.ac-cn-hongkong-c.wakuv2.prod | CHANGED | rc=0 >>
      --dns4-domain-name=node-01.ac-cn-hongkong-c.wakuv2.prod.statusim.net
```
