### ISSUE TITLE
Websocket connection issue

### ISSUE THREAD

**Issue by fryorcraken** [status-im/infra-nim-waku#56]
See log below, time is AEST (UTC+10)
 
```
15:21:04.961 Firefox can’t establish a connection to the server at wss://node-01.gc-us-central1-a.wakuv2.prod.statusim.net/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA.
```

It seems to be at websocket level (as it's a Firefox error, not a JS one)

**Comment by fryorcraken** [comment]
Doesn't seem to be a fluke as still occurring but only for this node

```
15:56:03.907 Firefox can’t establish a connection to the server at wss://node-01.gc-us-central1-a.wakuv2.prod.statusim.net/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA.
```

No problem connecting to `/dns4/node-01.do-ams3.wakuv2.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e ` for example.

**Comment by jakubgs** [comment]
I assume this is no longer relevant.

Also, if you just open an issue without assigning or pinging me I will probably not notice it until much, much later.
