### ISSUE TITLE
Connecting waku v2 test fleets to an Ethereum node on Goerli testnet

### ISSUE THREAD

**Issue by staheri14** [status-im/infra-nim-waku#59]
# Problem
As part of waku-rln-relay protocol, waku v2 nodes are supposed to listen to some events emitted from a smart contract deployed on Goerli testnet and perform some operations internally. The necessary code for this is already implemented that is right now waku v2 nides can accept the address of a node on Goerli testnet via a dedicated config parameter i.e., [`eth-client-address`](https://github.com/status-im/nwaku/blob/051f5db9afb281938710f54398972934647786fa/waku/v2/node/config.nim#L162) which is the websocket address of a node (e.g., Infura). Once passed, the waku node makes the necessary connections  for event subscription and further communication. 

The current issue is to explore how it should be done on waku test fleets. My understanding is that 1) we need to have the address of an Ethereum node on Goerli testnet to which waku test fleets can connect 2) the corresponding config option `eth-client-address` should be added to https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-test.yml#L45 similar to other rln-relay parameters.

**Comment by jakubgs** [comment]
Does this have to be a dedicated Geth node on Goerli testnet, or would it be fine to connect to one of the Nimbus ones?

**Comment by jakubgs** [comment]
After discussing this with @staheri14 it appears it should be fine to use some of the Geth nodes we've deployed for Nimbus.

This will make this much simpler, and also cheaper.

**Comment by staheri14** [comment]
> I see no space for a JWT secret, so I assume there's only support for plain RPC:

Ethereum clients implement a suite of JSON-RPC methods.

**Comment by jakubgs** [comment]
The main way CL clients communicate with EL clients is using [Auth RPC](https://geth.ethereum.org/docs/interface/consensus-clients), not plain RPC. That's what I'm referring to.

**Comment by jakubgs** [comment]
Change has been deployed:

- https://github.com/status-im/infra-nimbus/commit/414923bf - nimbus.prater: open Geth RPC ports for wakuv2 fleets
- https://github.com/status-im/infra-nim-waku/commit/5a47a72a - wakuv2-test: use nimbus.prater node for eth client

Result:
```
 > a all -a 'grep eth-client /docker/nim-waku-v2/docker-compose.yml'  
node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
      --eth-client-address=http://linux-01.he-eu-hel1.nimbus.prater.wg:8546
node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
      --eth-client-address=http://linux-01.he-eu-hel1.nimbus.prater.wg:8546
node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
      --eth-client-address=http://linux-01.he-eu-hel1.nimbus.prater.wg:8546
```
I'm using just the first Geth node from `linux-01.he-eu-hel1.nimbus.prater.wg` but if we want to in thee future we could have each node using it's own dedicated Geth node.

**Comment by jakubgs** [comment]
Some more not exactly related fixes:

- https://github.com/status-im/infra-role-nim-waku/commit/57c296a4 - consul: re-enable websocket healthcheck
- https://github.com/status-im/infra-role-nim-waku/commit/edfeed3b - consul: use 127.0.0.1 instead of localhost
- https://github.com/status-im/infra-role-nim-waku/commit/d892e19d - docker: fix eth client address flag check

**Comment by staheri14** [comment]
> http

Thanks a lot @jakubgs for taking care of this!

The client addresses are `HTTP`, can we please pass a WebSocket address instead?

**Comment by jakubgs** [comment]
Okay. Don't you think the flag should indicate in the help message that it expects a websocket?

**Comment by jakubgs** [comment]
Fixed:

- https://github.com/status-im/infra-nimbus/commit/fa3bb886 - nimbus.prater: open websocket port for wakuv2.test
- https://github.com/status-im/infra-nim-waku/commit/725ff4a7 - wakuv2-test: use websocket port for eth client
- https://github.com/status-im/infra-nimbus/commit/1f54ea1f - nimbus.prater: open websocket port to other hosts

```
 > a all -a 'grep eth-client /docker/nim-waku-v2/docker-compose.yml' 
node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
      --eth-client-address=ws://linux-01.he-eu-hel1.nimbus.prater.wg:9547
node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
      --eth-client-address=ws://linux-01.he-eu-hel1.nimbus.prater.wg:9547
node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
      --eth-client-address=ws://linux-01.he-eu-hel1.nimbus.prater.wg:9547
```

**Comment by staheri14** [comment]
> Okay. Don't you think the flag should indicate in the help message that it expects a websocket?

You are right, although the example address in the help message is a WebSocket address, it is not sufficient and needs to be explicitly stated as well.

**Comment by staheri14** [comment]
> Fixed:
> 
> * [status-im/infra-nimbus@fa3bb886](https://github.com/status-im/infra-nimbus/commit/fa3bb886) - nimbus.prater: open websocket port for wakuv2.test
> * [status-im/infra-nimbus@1f54ea1f](https://github.com/status-im/infra-nimbus/commit/1f54ea1f) - nimbus.prater: open websocket port to other hosts
> * [725ff4a7](https://github.com/status-im/infra-nim-waku/commit/725ff4a7) - wakuv2-test: use websocket port for eth client
> 
> ```
>  > a all -a 'grep eth-client /docker/nim-waku-v2/docker-compose.yml' 
> node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
>       --eth-client-address=ws://linux-01.he-eu-hel1.nimbus.prater.wg:9547
> node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
>       --eth-client-address=ws://linux-01.he-eu-hel1.nimbus.prater.wg:9547
> node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
>       --eth-client-address=ws://linux-01.he-eu-hel1.nimbus.prater.wg:9547
> ```

Thanks a lot for updating the addresses!
