### ISSUE TITLE
bug: deployed DNS lists for `wakuv2.*` fleets contain wrong ENR

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-nim-waku#64]
### Problem

As part of automating Merkle tree lists for DNS discovery in the `status.*` fleets, we also updated the deployed DNS lists for the `wakuv2.*` fleets. However, the ENRs in the deployed lists _only for the `wakuv2.*` fleets_ are incomplete as reported in https://github.com/waku-org/nwaku/issues/1464. The lists for `status.*` fleets are correct.

Not sure how this happened, as a quick scan through the current logs indicate that the nodes themselves log the correct ENRs and should provide the correct ones as response to `info` requests. It may be that some inconsistency/outdated versions of `nwaku` were running at the time of list deployment.

### What should be done?

1. Verify from at least one node in a `wakuv2.*` fleet that it provides a complete ENR in response to `info` RPC requests. Afaik these responses are used to scrape the ENR records as source for deployed lists. For our fleets, a "complete" ENR in decoded form:
- [ ] usually ends in `TIP` or `Mg8` (not `Dw`), or
- [ ] contains a `multiaddrs` field when pasted and decoded into https://enr-viewer.com/
2. If (1) successful, trigger [the deployment script](https://github.com/status-im/infra-utils/blob/aedd1176f6cfc8086b3c6fb9ec486ace39112b0e/consul/dnsdisc.py) to redeploy the lists for the `wakuv2.*` fleets with the correct ENRs.

**Comment by jakubgs** [comment]
Looks correct to me:
```
 > curl -sL fleets.status.im | jq -r '.fleets["wakuv2.prod"]["enr/p2p/waku"][]' | grep -o '...$'
Mg8
TIP
TIP

 > curl -sL fleets.status.im | jq -r '.fleets["wakuv2.test"]["enr/p2p/waku"][]' | grep -o '...$'    
Mg8
TIP
TIP
```

**Comment by jm-clius** [comment]
Indeed. Thanks! Those are the correct ENRs. These should be deployed to `test.waku.nodes.status.im` and `prod.waku.nodes.status.im` which for some reason are all `yDw`.

**Comment by jakubgs** [comment]
Updated:
```
 > ./dnsdisc.py -d test.waku.nodes.status.im -n nim-waku-v2-enr -e wakuv2 -s test 
[INFO] Service found: node-01.do-ams3.wakuv2.test:nim-waku-v2-enr
[INFO] Service found: node-01.gc-us-central1-a.wakuv2.test:nim-waku-v2-enr
[INFO] Service found: node-01.ac-cn-hongkong-c.wakuv2.test:nim-waku-v2-enr
[INFO] Deleting record: 3s6uuuu5pemvs6hn5sf7tqi4a4.test.waku.nodes.status.im
[INFO] Deleting record: kbrq4xg3y56bynq5r3zlzrk6ou.test.waku.nodes.status.im
[INFO] Deleting record: test.waku.nodes.status.im
[INFO] Deleting record: u63w4rlnra74mkwkr2zftrvzqu.test.waku.nodes.status.im
[INFO] Deleting record: xm2q6nsaqrmhdujnnomabbxcma.test.waku.nodes.status.im
[INFO] Creating record: egf7dj6ceodmebfe2uf7xqoaai.test.waku.nodes.status.im
[INFO] Creating record: ojslbzj7kbwlz4ye6ywkl2dzi4.test.waku.nodes.status.im
[INFO] Creating record: qefjr3efyo2jgmvutdw43rdms4.test.waku.nodes.status.im
[INFO] Creating record: test.waku.nodes.status.im
[INFO] Creating record: wf4lispxf3qrmzuoiullvlx6m4.test.waku.nodes.status.im
[INFO] URL: enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@test.waku.nodes.status.im
```
```
 > ./dnsdisc.py -d prod.waku.nodes.status.im -n nim-waku-v2-enr -e wakuv2 -s prod    
[INFO] Service found: node-01.do-ams3.wakuv2.prod:nim-waku-v2-enr
[INFO] Service found: node-01.gc-us-central1-a.wakuv2.prod:nim-waku-v2-enr
[INFO] Service found: node-01.ac-cn-hongkong-c.wakuv2.prod:nim-waku-v2-enr
[INFO] Deleting record: 7wv4enn3okrx2ug7pxeascptxu.prod.waku.nodes.status.im
[INFO] Deleting record: kmkofs2a5ugz7lzmmzyyljhp3a.prod.waku.nodes.status.im
[INFO] Deleting record: prod.waku.nodes.status.im
[INFO] Deleting record: pwuxh5pqx3gng5pztiaj4ong5y.prod.waku.nodes.status.im
[INFO] Deleting record: tfu64z6lgc7a2klo4blnrjuabu.prod.waku.nodes.status.im
[INFO] Creating record: duswqsjuobvm6cgrivke7towvq.prod.waku.nodes.status.im
[INFO] Creating record: ichvqp6rkghsscg6ijhfiptcwe.prod.waku.nodes.status.im
[INFO] Creating record: j3eapx7uxjg3pzofwyxg6haohu.prod.waku.nodes.status.im
[INFO] Creating record: prod.waku.nodes.status.im
[INFO] Creating record: u3li4k3loyrzpq22xcbtu7oj3y.prod.waku.nodes.status.im
[INFO] URL: enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im
```
