### ISSUE TITLE
Static sharding & Postgres

### ISSUE THREAD

**Issue by SionoiS** [status-im/infra-nim-waku#74]
Hi,

@Ivansete-status and me are in need of a fleet for static sharding and the new DB.

Configuring nwaku for static shard is just a matter of changing the pubsub topics but for the DB I'm not sure, I'll let Ivan explain.

We seek guidance on this, O great infra master :P

I was thinking of copying waku2.test then modify it for our needs? What else do we need?

**Comment by Ivansete-status** [comment]
Thanks for submitting that @SionoiS !
I think it is a good approach to have the `wakuv2.test` as a reference.
Re the Postgres feature, we need to have a separate node that will host the Postgres itself. Then, in this "staging" fleet we will have four nodes (3 nwaku + 1 postgres.)

cc - @jm-clius

**Comment by SionoiS** [comment]
> Thanks for submitting that @SionoiS ! I think it is a good approach to have the `wakuv2.test` as a reference. Re the Postgres feature, we need to have a separate node that will host the Postgres itself. Then, in this "staging" fleet we will have four nodes (3 nwaku + 1 postgres.)
> 
> cc - @jm-clius

Maybe more then 4 nodes. Depends if testing only 2 shards is sufficient (probably not).

**Comment by jm-clius** [comment]
> > Thanks for submitting that @SionoiS ! I think it is a good approach to have the `wakuv2.test` as a reference. Re the Postgres feature, we need to have a separate node that will host the Postgres itself. Then, in this "staging" fleet we will have four nodes (3 nwaku + 1 postgres.)
> > cc - @jm-clius
> 
> Maybe more then 4 nodes. Depends if testing only 2 shards is sufficient (probably not)

Number of nodes doesn't have to equal the number of shards. In fact all nodes should support the same shards and likely ~10 in total. I think we can come up with more precise requirements here. Let's discuss in nwaku-PM call and be specific here (i.e. which shards, how to set up the postgresql settings and what services should be enabled here).

**Comment by SionoiS** [comment]
### Static Sharding
Cluster 16 is reversed for status main net according to RFC52 shall we use cluster 18 for test net?
For shards indices, 896+ for controls, 768+ for 1on1, 128+ for small communities, 16+ for large communities and maybe more then 1 shard per category? Let say 3.

Topics;
```
/waku/2/18/16
/waku/2/18/17
/waku/2/18/18
/waku/2/18/128
/waku/2/18/129
/waku/2/18/130
/waku/2/18/768
/waku/2/18/769
/waku/2/18/770
/waku/2/18/896
/waku/2/18/897
/waku/2/18/896
```

### Protocols
At least one Store node to test new DB, LightPush, Filter, Peer Exchange, RLN and Relay
For DOS protection, [see RFC57 for guidance](https://rfc.vac.dev/spec/57/#dos-protection)

Otherwise will use the default values from wakuv2-test.yml

**Comment by Ivansete-status** [comment]
@jakubgs - Re Postgres we need to pass a param analog to the next one, to each `nwaku` node:

`store-message-db-url = "postgres://postgres:test123@localhost:5432/postgres"`

Obviously, the user (test1234) and the password (5432) should be changed and cannot be written in GitHub. We need to keep them secret :)

On the other hand, the `localhost` should be replaced by the IP of the instance that hosts the Postgres database.

We should be able to interact with the Postgres database from within its own host through the `psql` command.

As we've mentioned, we'll only have one Postgres instance for now. I suggest having it in the AMS data center.

Thanks in advance!

**Comment by jakubgs** [comment]
You know, just because you open an issue in a repo doesn't mean I will see it. You actually have to ping me, like the comment above did, otherwise I will never see it.

**Comment by jakubgs** [comment]
>On the other hand, the localhost should be replaced by the IP of the instance that hosts the Postgres database.

Lol, really, I wouldn't have guessed :D. Hahahaha

**Comment by jakubgs** [comment]
We already have a Postgres setup for `status-go` nodes:
https://github.com/status-im/infra-role-status-go/blob/3e52ec695ac4c807ca01b28f908a943b8a0b545b/templates/docker-compose.yml.j2#L55-L80

I assume in this case it would also be optional and enabled by a flag.

**Comment by jakubgs** [comment]
Also, can someone explain to em what this PR was for and why it was closed? Is it related?

* https://github.com/status-im/infra-wakuv2/pull/75

**Comment by SionoiS** [comment]
> Also, can someone explain to em what this PR was for and why it was closed? Is it related?
> 
> * [New fleet Initialization #75](https://github.com/status-im/infra-wakuv2/pull/75)

At first I thought I was going to setup the fleet but the process seams to be that we ask and specify what we need to you @jakubgs

Is that how it work usually?

**Comment by jakubgs** [comment]
I welcome PRs, since they save me time in the long run. That PR looked pretty sensible, maybe a few things to fix.

**Comment by SionoiS** [comment]
> I welcome PRs, since they save me time in the long run. That PR looked pretty sensible, maybe a few things to fix.

@jakubgs If you can reopen the PR I'll make the changes and we can continue.

**Comment by SionoiS** [comment]
> I welcome PRs, since they save me time in the long run. That PR looked pretty sensible, maybe a few things to fix.

I'll make the changes then we can continue.

**Comment by SionoiS** [comment]
Sorry for the mess @jakubgs nobody noticed the problem with the config.

**Comment by jakubgs** [comment]
Shit happens when you move fast.

**Comment by Ivansete-status** [comment]
As per the Postgres configuration, we need the next topology in the [wakuv2.shards](https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-shards.yml) fleet:

One single Postgres DB instance running in Amsterdam DC.
The three nodes should be connected to the ams db instance.

A parameter similar to the next one should be passed to the `nwaku` nodes.
```
--store-message-db-url='postgres://postgres:test123@localhost:5432/postgres'
```

**Comment by jakubgs** [comment]
@Ivansete-status is this request separate from:

* https://github.com/status-im/infra-status/issues/27

Or is it just an early version of that issue and now outdated?

I don't think this repo can hold such a drastically different setup.
Unless we actually want to apply it to all other stages in this fleet.

**Comment by Ivansete-status** [comment]
Hey @jakubgs !
This is a separate request. In this case, the purpose of having such a layout is to ensure we test the next use case:
"Multiple writers writing to a single postgresql DB in a real network environment".

This fleet is for testing purposes. If that setup doesn't fit well with the rest, we can seek another one.

( cc @jm-clius )

**Comment by jakubgs** [comment]
Isn't this just a test stage for what you want to do in:

* https://github.com/status-im/infra-status/issues/27

It seems like we just got confused by not knowing your future goal and put this fleet here for lack of a better place.
But really, it should belong, in the new repo where the fleet requested by https://github.com/status-im/infra-status/issues/27 will be created.

**Comment by Ivansete-status** [comment]
@jakubgs @yakimant - from the next repo, a `nwaku` node instance + _Postgres_ can be started with `docker compose up`.

https://github.com/waku-org/nwaku-compose

Checking the Grafana dashboard from `localhost:3000` (admin - admin)

![image](https://github.com/status-im/infra-nim-waku/assets/128452529/fd6c068f-cdbd-41a9-98c5-bbb368260cf3)

**Comment by jm-clius** [comment]
Afaik the `wakuv2.shards` fleet is being used to dogfood some aspects related to Status static sharding, but dogfooding efforts will focus on the new `status.shards` fleet as soon as this is ready. I therefore propose to deprioritise the postgresql installation for `wakuv2.shards` and instead focus on `status.shards`.

**Comment by yakimant** [comment]
@jm-clius, @Ivansete-status, I just decomissioned `wakuv2.shards`: https://github.com/status-im/infra-nim-waku/pull/88

I guess this Issues should be closed now in favour of:
- `waku.test` (https://github.com/status-im/infra-nim-waku/pull/82)
- `shards.test` (https://github.com/status-im/infra-shards/issues/2)

fleets
