### ISSUE TITLE
Recurrent disk limitation in wakuv2.prod fleet

### ISSUE THREAD

**Issue by apentori** [status-im/infra-nim-waku#86]
# Problem

The node of the `wakuv2.prod` fleet are often getting out of disk space.

# Current configuration

The fleet is configure to have a 30 day retention policy.

# Observations

* Before last cleanup, the database take ~32GB for 6.13 Millions messages.
* In 5 days after the deletion, the database takes 6.8GB for 1.315 M messages. 

The message size is similar in both case (5.16 KB/msg and ~5.2 KB/msg), no deletion was done by waku before the cleanup.
With disk of 40 GB, each with this size per message, we can store around 28 / 29 days of messages (~7.5 Millions messages)
Therefore adding the vacuum for this stage won't solve the issue if we keep the limitation at 30 days.

> *Note*: 
> * In sqlite, deleting data doesn't free disk space, a vacuum has to be done.
> * To performe a Vacuum in sqlite, a significant portion of the disk need to be available.
> * Waku Vacuum is done only when the node is starting.

# Solution ideas

* Lower the max message number (either by reducing the retention period or by limiting the max number of messages) and adding a regular vacuum to the db.
* Increase the disk size  and add a regular vacuum to free the space of  deleted message.

**Comment by apentori** [comment]
The same problem happen to the ``status.prod`` fleet which hold important data.

To solve the current issue without losing data, on each host we could : 
* Mount an additional  volume (twice the current db size),
* stop the wakunode service
* perform the vacuum with the variable `SQLITE_TMPDIR`  pointing to the additional volume
* Unmount the volume
* restart service

**Comment by jakubgs** [comment]
This fleet has only one host now  - `node-01.do-ams3.wakuv2.prod` - and will be decommissioned once `js-waku` project supports static sharding.
